### ISSUE TITLE
Fireworks stay on same place

### ISSUE THREAD

**Issue by sitolam** [cj0x39e/flutter_confetti#1]
The fireworks code that is mentioned on the website stays on the same place on my app. It starts on a random place but stays there.

**Comment by tao-zhi-1992** [comment]
Hello @sitolam. The place where the confetti is shown is according to the x and the y values(like the below codes), and you can print the x and the y values on each call to ensure that they are different values.

```dart
ConfettiOptions(
         ...
          x: randomInRange(0.1, 0.3),
          y: Random().nextDouble() - 0.2),
         ...
)
```

If you still face the issue, you can paste your code here.

**Comment by sitolam** [comment]
I figured it out I just needed to remove the two if statements. Love the project 😜
