### ISSUE TITLE
blast a emoji

### ISSUE THREAD

**Issue by nosuke0926** [cj0x39e/flutter_confetti#3]
thank you for the great package btw, I would like to know is there any way to blast an emoji, it would be great if you have any solution about this.

**Comment by cj0x39e** [comment]
@cj0x39e I will add the feature in a few days.

**Comment by tao-zhi-1992** [comment]
@nosuke0926  I will add the feature in a few days.

**Comment by nosuke0926** [comment]
@cj0x39e Thank you so much for your kind words and for your quick response!

**Comment by tao-zhi-1992** [comment]
@nosuke0926 I have published 0.3.2, which comes with the emoji [demo](https://cj0x39e.github.io/flutter_confetti/) and the document: [How to use emoji](https://github.com/cj0x39e/flutter_confetti?tab=readme-ov-file#how-to-use-emoji)
