### ISSUE TITLE
Dismiss confetti feature?

### ISSUE THREAD

**Issue by istornz** [cj0x39e/flutter_confetti#4]
Hello, first thanks for the awesome package!
I'm wondering if there is a possibility to dismiss confetti?

I want to clear the screen by executing a method for example `clearParticles()` 

Thanks !

**Comment by tao-zhi-1992** [comment]
@istornz  It's possible, but I need to add a method to the controller. I will have it done in a few days.

**Comment by tao-zhi-1992** [comment]
@istornz Hello, in the latest version  (0.3.4) you can call the `controller.kill()` method to clear the screen. I have added a killing example in the [Live web demo](https://cj0x39e.github.io/flutter_confetti/).

**Comment by istornz** [comment]
Nice thanks!
